services:
  postgres:
    container_name: postgres
    build:
      context: './requirements/postgresql'
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - ft_transcendence
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  backend:
    container_name: backend
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - USE_S3=TRUE
      - AWS_ACCESS_KEY_ID=UPDATE_ME
      - AWS_SECRET_ACCESS_KEY=UPDATE_ME
      - AWS_STORAGE_BUCKET_NAME=UPDATE_ME
    networks:
      - ft_transcendence
    expose:
      - 8000
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m
      timeout: 10s
      retries: 5

  frontend:
    container_name: frontend
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
    networks:
      - ft_transcendence
    volumes:
      - frontend_build:/usr/src/app/dist
    restart: "no"
    healthcheck:
      test: ["CMD", "test", "-f", "/usr/src/app/build/index.html"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      # - "80:80"
      - "8080:8080"
      - "4443:443"
    volumes:
      - frontend_build:/usr/share/nginx/html
    networks:
      - ft_transcendence
    depends_on:
      - frontend
      - backend
    secrets:
      - ssl_certificate
      - ssl_certificate_key
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5

  portainer:
    image: portainer/portainer-ce:latest
    networks:
      - ft_transcendence
    container_name: portainer
    restart: on-failure
    ports:
      - "1313:9000"  # Portainer UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    # environment:
    #   TZ: "Your/Timezone"  # Optional: Replace with your timezone (e.g., "Etc/UTC" or "America/New_York")


networks:
  ft_transcendence:
    driver: bridge

volumes:
  frontend_build:
  static_volume:
  media_volume:
  database-postgres:
  postgres_data:
  portainer_data:

secrets:
  ssl_certificate:
    file: ../secrets/ssl/certificate.crt
  ssl_certificate_key:
    file: ../secrets/ssl/certificate.key
